version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
        environment:
          GO111MODULE: "on"
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-{{ checksum "go.sum" }}
      - run: go test -tags coverage -coverprofile=coverage.txt -covermode=atomic ./pkg/saku
      - save_cache:
          key: v1-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run: bash <(curl -s https://codecov.io/bash)
