version: 2
jobs:
  build:
    environment:
      GOPATH: /
      GOCACHE: /.cache/go-build
      GO111MODULE: on
    working_directory: /workspace
    docker:
      - image: circleci/golang:1.11
    steps:
      - checkout
      - restore_cache:
          key:
            - v1-{{ checksum "/workspace/go.sum" }}
            - v1-

      - run: cd pkg/saku; go test -tags coverage -coverprofile=coverage.txt -covermode=atomic .
      - save_cache:
          key: v1-{{ checksum "/workspace/go.sum" }}
          paths:
            - "/workspace"
      - run: bash <(curl -s https://codecov.io/bash)
